# -*- coding: utf-8 -*-
"""Factorial

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sk2Ap8vL2Hq5VGIkTyi7OvyO04fDlRDZ
"""

factorial


n=5
fact=1
for i in range(1, n + 1):

    fact = fact * i
print(f"Factorial of {n} = {fact}")
Factorial of 5 = 120